version: 2
jobs:

  deploy:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Run all the things
          command: |
            make all
            git config credential.helper 'cache --timeout=120'
            git config user.email "enrico.stahn@gmail.com"
            git config user.name "Enrico Stahn"
            git add .
            git commit -m "chore: update godownloader scripts via CircleCI" .
            git push -q https://${GITHUB_TOKEN}@github.com/estahn/godownloader.git master

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy:
          context: org-global
