version: 2
jobs:

  deploy:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: make all

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy:
          context: org-global
